name: "SQLite Database Operations"
description: "Manages SQLite database operations: restore from diffable dump or dump to diffable format"
inputs:
  operation:
    description: "Operation to perform: restore or dump"
    required: true
  db_path:
    description: "Path to the SQLite database file"
    required: true
    default: "data/db.sqlite"
  dump_dir:
    description: "Directory where diffable dump should be stored (for dump operation)"
    required: true
    default: "data/dump"

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Restore SQLite database from diffable dump
      if: inputs.operation == 'restore'
      shell: bash
      run: |
        set -euo pipefail
        # Check if dump directory exists
        DUMP_DIR='${{ inputs.dump_dir }}'
        TARGET_DB='${{ inputs.db_path }}'

        if [ ! -d "$DUMP_DIR" ]; then
          echo "⚠️ Warning: Dump directory $DUMP_DIR does not exist or is empty"
          echo "⏭️ Skipping database restore"
          exit 0
        fi

        # Create target directory if it doesn't exist
        mkdir -p $(dirname $TARGET_DB)

        # Load the database from the diffable dump
        echo "🔄 Restoring database from diffable dump..."
        uv run uvx sqlite-diffable load $TARGET_DB $DUMP_DIR --replace

        # Verify the database was restored successfully
        echo "✅ Database restored to $TARGET_DB"
        echo "📋 Checking database..."
        ls -la $(dirname $TARGET_DB)

        # Only run if sqlite3 is available
        if command -v sqlite3 &> /dev/null; then
          echo "📊 Database tables:"
          sqlite3 $TARGET_DB ".tables" || echo "Could not query tables (this is normal if the database is empty)"
        fi

    - name: Dump SQLite database to diffable format
      if: inputs.operation == 'dump'
      shell: bash
      run: |
        # Check if database file exists
        if [ ! -f "${{ inputs.db_path }}" ]; then
          echo "⚠️ Warning: Database file ${{ inputs.db_path }} does not exist"
          exit 1
        fi

        # Create dump directory if it doesn't exist
        mkdir -p ${{ inputs.dump_dir }}

        # Dump the database to diffable format
        echo "🔄 Dumping database to diffable format..."
        uv run uvx sqlite-diffable dump ${{ inputs.db_path }} ${{ inputs.dump_dir }} --all

        # Verify the dump was created successfully
        echo "✅ Database dumped to ${{ inputs.dump_dir }}"
        echo "📋 Checking dump directory..."
        ls -la ${{ inputs.dump_dir }}

        # Remove Drizzle migration tables from dump
        echo "🧹 Removing migration tables from dump..."
        rm -f ${{ inputs.dump_dir }}/__drizzle_migrations*
