name: "Setup Pipeline Data Branch"
description: "Sets up a worktree for the pipeline-data branch and syncs data"
inputs:
  operation:
    description: "Operation to perform: setup, update, or cleanup"
    required: true
  source_path:
    description: "Source path to copy data from (for update operation), relative to the main workspace"
    required: false
    default: "./data/"
  exclude_pattern:
    description: "Pattern to exclude when copying files"
    required: false
    default: "*.sqlite"
  commit_message:
    description: "Commit message for updates"
    required: false
    default: 'Pipeline run: $(date -u +"%Y-%m-%d %H:%M")'
  branch_name:
    description: "Name of the branch to store pipeline data"
    required: false
    default: "pipeline-data"

runs:
  using: "composite"
  steps:
    # Setup operation - creates worktree and copies data to workspace
    - name: Setup pipeline-data branch
      if: inputs.operation == 'setup'
      shell: bash
      run: |
        mkdir -p data
        # Configure git
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

        # Check if pipeline-data branch exists
        if git ls-remote --heads origin ${{ inputs.branch_name }} | grep ${{ inputs.branch_name }}; then
          echo "Pipeline data branch exists, retrieving data..."
          
          # Create a worktree for pipeline-data branch and check out the branch directly
          git fetch origin ${{ inputs.branch_name }}
          git worktree add pipeline-data-worktree origin/${{ inputs.branch_name }}
          
          # Copy data files to main workspace
          cp -r pipeline-data-worktree/data/. data/ 2>/dev/null || echo "No data files found in pipeline-data branch"
        else
          echo "Creating new pipeline-data branch..."
          
          # Create a worktree with new orphan branch
          git worktree add --detach pipeline-data-worktree
          cd pipeline-data-worktree
          git checkout --orphan ${{ inputs.branch_name }}
          git rm -rf . 2>/dev/null || true
          
          # Create .gitignore that only keeps data folder
          echo "# Ignore everything except data directory" > .gitignore
          echo "/*" >> .gitignore
          echo "!data/" >> .gitignore
          echo "!.gitignore" >> .gitignore
          echo "!README.md" >> .gitignore
          echo "" >> .gitignore
          echo "# Exclude database file" >> .gitignore
          echo "data/db.sqlite" >> .gitignore
          
          # Create a README
          echo "# Pipeline Data" > README.md
          echo "This branch contains data files generated by the pipeline. Do not modify manually." >> README.md
          
          git add .gitignore README.md
          git commit -m "Initialize pipeline-data branch" || true
          
          # Push the new branch to the remote
          git push -u origin ${{ inputs.branch_name }}
          cd ..
        fi

    # Update operation - copies data from workspace to pipeline-data branch and commits
    - name: Update pipeline-data branch
      if: inputs.operation == 'update'
      shell: bash
      run: |
        cd pipeline-data-worktree

        # Ensure data directory exists
        mkdir -p data

        # Copy current data files from main workspace to pipeline-data branch
        # Use rsync if available for more efficient copying (only changed files)
        if command -v rsync &> /dev/null; then
          rsync -av --delete ../${{ inputs.source_path }} data/ --exclude=${{ inputs.exclude_pattern }}
        else
          rm -rf data/dump/ data/summaries/ 2>/dev/null || true  # Clean old directories if they exist
          cp -r ../${{ inputs.source_path }}. data/ 2>/dev/null || true
        fi

        # Add and commit changes
        git add -A data/
        git status
        git commit -m "${{ inputs.commit_message }}" || echo "No changes to commit"

        # Push with error handling
        if ! git push origin HEAD:${{ inputs.branch_name }}; then
          echo "Failed to push normally. Checking for conflicts..."
          
          # Fetch latest changes
          git fetch origin ${{ inputs.branch_name }}
          
          # Show a concise summary of what would be overwritten
          echo "Summary of changes that would be overwritten:"
          echo "=== Files changed in remote that differ from local ==="
          git diff --name-status origin/${{ inputs.branch_name }}..HEAD
          
          echo "=== Number of conflicting files ==="
          git diff --name-only origin/${{ inputs.branch_name }}..HEAD | wc -l
          
          echo "=== Size of changes (lines added/removed) ==="
          git diff --shortstat origin/${{ inputs.branch_name }}..HEAD
          
          echo "Force pushing changes..."
          # Ensure we're on the correct branch and it exists
          CURRENT_BRANCH=$(git branch --show-current)
          echo "Current branch: $CURRENT_BRANCH"
          
          # Make sure we're pushing the current HEAD to the correct branch reference
          if ! git push --force origin HEAD:${{ inputs.branch_name }} 2>&1; then
            echo "Error: Force push failed with the following error:"
            git push --force origin HEAD:${{ inputs.branch_name }} 2>&1 || echo "Exit code: $?"
            exit 1
          fi
        fi
        cd ..

    # Cleanup operation - removes the worktree
    - name: Cleanup worktree
      if: inputs.operation == 'cleanup'
      shell: bash
      run: git worktree remove pipeline-data-worktree || true
