name: Deploy Data to GitHub Pages

on:
  push:
    branches: ["_data"]
  workflow_dispatch:
  workflow_run:
    workflows: ["Generate Summaries"]
    branches: [main]
    types: [completed]

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout _data branch
        uses: actions/checkout@v4
        with:
          ref: _data

      - name: Get today's date and copy stats
        run: |
          cp data/stats/$(date +'%Y-%m-%d').json data/stats.json

      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: data

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
